version: "3.8" # Docker Compose file format version
services:
  mongo: # Service name for MongoDB
    image: mongo:latest # Uses the latest MongoDB image from Docker Hub
    restart: always # Automatically restarts if it crashes
    ports:
      - "27017:27017" # Maps container port to host port (host:container)
    volumes:
      - mongo_data:/data/db # Persists data between container restarts
    environment:
      - MONGO_INITDB_DATABASE=system-flow # Creates this database on startup
volumes: # Defines named volumes that persist data
  mongo_data: # MongoDB data storage
